title: Oxibase
description: High-performance embedded SQL database written in pure Rust
url: https://oxibase.xyz
repository_url: https://github.com/oxibase/oxibase

# Google Analytics
google_analytics:

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .gitignore

# Collections for documentation
collections:
  docs:
    output: true
    permalink: /:collection/:path/
    sort_by: order

theme: just-the-docs
logo: "/assets/img/logo-horizontal.svg"

# Color scheme
color_scheme: blue

just_the_docs:
  collections:
    docs:

# Default layouts
defaults:
   - scope:
       path: ""
       type: "docs"
     values:
       layout: "default"
   - scope:
       path: ""
     values:
       layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Syntax highlighting with Rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge

enable_copy_code_button: true

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.12.2"

sass:
  quiet_deps: true

aux_links:
  "GitHub":
    - "//github.com/oxibase/oxibase"

footer_content: "Copyright &copy; 2025-2026 Oxibase Contributors. Gabriel Maeztu."
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/oxibase/oxibase" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from

