title: Oxibase
description: High-performance embedded SQL database written in pure Rust
url: https://oxibase.io
repository_url: https://github.com/oxibase/oxibase

# Google Analytics
google_analytics:

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .gitignore

# Collections for documentation
collections:
  docs:
    output: true
    permalink: /:collection/:path/
    sort_by: order

theme: just-the-docs
logo: "/assets/img/logo-horizontal.svg"

just_the_docs:
  collections:
    docs:

# Default layouts
defaults:
   - scope:
       path: ""
       type: "docs"
     values:
       layout: "default"
   - scope:
       path: ""
     values:
       layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Syntax highlighting with Rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.12.2"
